### ISSUE TITLE
automate onboarding this repo and setting up local dev env for mac

### ISSUE THREAD

**Issue by carloshgaray** [livgust/covid-vaccine-scrapers#2]
I'm currently seeing this issue after having followed instructions:

```bash
> node main.js
DEV MODE
/Users/cgaray/dev/covid/ora/covid-vaccine-scrapers/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
            reject(new Error([
                   ^

Error: Failed to launch the browser process! spawn /Applications/Chromium ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Users/cgaray/dev/covid/ora/covid-vaccine-scrapers/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/Users/cgaray/dev/covid/ora/covid-vaccine-scrapers/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:378:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

```

```bash
> node --version
v15.8.0
```

**Comment by tkjones117** [comment]
@carloshgaray where is your `Chromium` executable? And what is in your .env file - I assume just `/Applications/Chromium`?

My `Chromium` is here: `/Applications/Chromium.app/Contents/MacOS/Chromium` - I moved it there from my Downloads after downloading. 
And my .env file has: `CHROMEPATH="/Applications/Chromium.app/Contents/MacOS/Chromium"`

**Comment by livgust** [comment]
@tkjones117 we're hopping on a Zoom to work on this if you're interested.

**Comment by tkjones117** [comment]
sure! you can post here or email me at (github username)@gmail.com

**Comment by tkjones117** [comment]
PR https://github.com/livgust/covid-vaccine-scrapers/pull/1 will make this clearer :)
